# Generated by Django 5.1.4 on 2025-01-24 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_alter_record_creation_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ['-creation_date']},
        ),
    ]
