# Generated by Django 5.1.4 on 2025-01-22 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_alter_record_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bazar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('item_name', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('unit', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'kg'), (2, 'L')], null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('done_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bazar', to=settings.AUTH_USER_MODEL)),
                ('mess', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bazar', to='webapp.mess')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
