# Generated by Django 5.1.4 on 2025-01-22 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_bazar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bazar',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='record',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
