# Generated by Django 5.1.4 on 2025-01-25 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_alter_bazar_price_alter_record_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bazar',
            name='unit',
            field=models.CharField(blank=True, choices=[('kg', 'kg'), ('L', 'L')], max_length=5, null=True),
        ),
    ]
