# Generated by Django 5.1.4 on 2025-02-04 05:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_mealschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='mess',
            name='meal_update_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='NextDayMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lunch', models.IntegerField(default=0)),
                ('dinner', models.IntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('mess', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nextdaymeal', to='webapp.mess')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nextdaymeal', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'mess', 'lunch', 'dinner')},
            },
        ),
    ]
