# Generated by Django 5.1.4 on 2025-02-04 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_mess_meal_update_time_nextdaymeal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nextdaymeal',
            name='date',
        ),
        migrations.AlterField(
            model_name='mess',
            name='mess_code',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
