# Generated by Django 5.1.4 on 2025-02-04 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_remove_nextdaymeal_date_alter_mess_mess_code'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='nextdaymeal',
            unique_together={('user', 'lunch', 'dinner')},
        ),
        migrations.RemoveField(
            model_name='nextdaymeal',
            name='mess',
        ),
    ]
