# Generated by Django 5.1.4 on 2025-02-04 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_alter_nextdaymeal_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nextdaymeal',
            name='day',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
