# Generated by Django 5.1.4 on 2025-02-05 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_nextdaymeal_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nextdaymeal',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nextdaymeal', to=settings.AUTH_USER_MODEL),
        ),
    ]
