# Generated by Django 5.1.4 on 2025-02-05 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_mess_lunch_update_time_alter_mess_meal_update_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nextdaymeal',
            name='day',
            field=models.DateField(),
        ),
    ]
