# Generated by Django 5.1.4 on 2025-02-06 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0018_alter_nextdaymeal_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealschedule',
            name='dinner',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='mealschedule',
            name='lunch',
            field=models.IntegerField(default=1),
        ),
    ]
