# Generated by Django 5.1.4 on 2025-02-07 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0019_alter_mealschedule_dinner_alter_mealschedule_lunch'),
    ]

    operations = [
        migrations.AddField(
            model_name='nextdaymeal',
            name='mess',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nextdaymeal', to='webapp.mess'),
        ),
    ]
